# MatchingUtils
NumTopQID: 5
NumTopPID: 5
NumTopAliases: 10

# Postgres Database Configuration
psql:
  db: "wikidata"
  user: <<TODO_ADD_PSQL_USERNAME_HERE>>
  pwd: <<TODO_ADD_PSQL_PASSWORD_HERE>>

sparql:
  emit_types: true

# Session History Information
history:
  enabled: true
  directory: "./data/history"

prompt_builder:
  directory: "./prompts"

language_model:
  directory: "./cache"
  openai_api_key: <<TODO_ADD_OPENAI_API_KEY_HERE>>

# Label Embeddings
embeddings:
  directory: "./data/embeddings"
  alias_count: 20000000 
  batch_size:  100000   # Number of embeddings to store per file.
  count:       2000000  # Total number of embeddings to compute.
  transformer:
    model: "all-MiniLM-L6-v2"
    device: "cpu"
  server:
    host: "127.0.01"
    port: 43096

# Invertible Predicates
predicates:
  directory: "./data/predicates"
  non_invertible:
    rel_threshold: 0.01
    abs_threshold: 1000
